"""init tables

Revision ID: c26eaa164902
Revises: 
Create Date: 2019-05-24 20:46:21.362555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26eaa164902'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('_password', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cartoon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notsort', sa.String(length=500), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('user_cartoon', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_cartoon'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savecartoon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('seat', sa.String(length=500), nullable=True),
    sa.Column('cartoon_save', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartoon_save'], ['cartoon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savecartoon')
    op.drop_table('cartoon')
    op.drop_table('user')
    # ### end Alembic commands ###
